# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: packwiz-refresh
        name: Packwiz Refresh
        description: This hook runs the `packwiz refresh` command
        entry: ./scripts/packwiz-refresh.sh
        language: script
