name = "Siim's Simple Create"
author = "siim"
version = "1.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b270aba5d223ed52b7ae75690ebd594aa3faf6cd3b5bf91b625ff650e60fc0a6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
