name = "Siim's Create+"
author = "siim"
version = "1.0.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6a1ccd94b7a553c41644a253b13563cbea29d4364338ac3e1614ae779a3233f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
