name = "Siim's Simple Create"
author = "siim"
version = "1.0.0-beta.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36240e54fd88df4aca960441046da30475802ab20a925b42217ed529cf077383"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
