name = "Siim's Simple Create"
author = "siim"
version = "1.0.0-beta.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dd6d2e9d92bf47f3c9644ecfc8f5a01f9379dc40117ff724eb336b8bf9b392a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
